server {
    server_name obninskstation.ru www.obninskstation.ru;

    root /var/www/obninskstation.ru/html;
    index index.html;
    location = /fest  { return 301 https://amo.obninskstation.ru/; }
    location = /fest/ { return 301 https://amo.obninskstation.ru/; }

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/obninskstation.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/obninskstation.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.obninskstation.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = obninskstation.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name obninskstation.ru www.obninskstation.ru;
    return 404; # managed by Certbot




}